### ISSUE TITLE
Convert jUnit4 tests to jUnit5

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1568]
@danfaer has done huge work by migrating the biggest and the most complex modules (`concurrent-api`, `http-api`, and `http-netty`) from jUnit4 to jUnit5 in #1415 and #1521.

For those, who want to learn ServiceTalk API, experience it as a user, and start contributing it might be a good exercise to do a similar conversion for other modules.

Each pull request can convert only one module. There are plenty of modules that contain only a few test classes. Please, look at the referenced pull requests and make your work consistent with their style (how dependencies are declared, how parametrized tests are used, how timeout is configured, etc.).

The whole list of modules with tests:

- [x] `servicetalk-buffer-api` #1592
- [x] `servicetalk-buffer-netty` #1593
- [x] `servicetalk-client-api-internal` #1608
- [x] `servicetalk-client-api` #1612
- [x] `servicetalk-concurrent-api-internal` #1608
- [x] `servicetalk-concurrent-api` #1415
- [x] `servicetalk-concurrent-api-internal` #1658
- [x] `servicetalk-concurrent-api-test` #1658 
- [x] `servicetalk-concurrent-internal` #1779
- [x] `servicetalk-concurrent-jdkflow` #1624
- [x] `servicetalk-concurrent-reactivestreams` #1628
- [x] `servicetalk-concurrent-test-internal` #1658 
- [x] `servicetalk-data-jackson-jersey` #1645
- [x] `servicetalk-data-jackson` #1664
- [x] `servicetalk-data-protobuf` #1664
- [x] `servicetalk-dns-discovery-netty` #1607
- [x] `servicetalk-encoding-api` #1525
- [x] `servicetalk-encoding-netty` #1664
- [x] `servicetalk-grpc-api` #1660
- [x] `servicetalk-grpc-internal` #1501
- [x] `servicetalk-grpc-netty` #1660
- [x] `servicetalk-grpc-protobuf` #1660
- [x] `servicetalk-grpc-protoc` #1660
- [x] `servicetalk-http-api` #1521
- [x] `servicetalk-http-netty` #1521
- [x] `servicetalk-http-router-jersey` #1645
- [x] `servicetalk-http-router-predicate` #1659
- [x] `servicetalk-http-security-jersey` #1659
- [x] `servicetalk-http-utils` #1659
- [X] `servicetalk-loadbalancer`#1762
- [x] `servicetalk-log4j2-mdc-utils` #1664
- [x] `servicetalk-log4j2-mdc` #1664
- [x] `servicetalk-opentracing-asynccontext` #1603
- [x] `servicetalk-opentracing-http` #1604
- [x] `servicetalk-opentracing-inmemory` #1599
- [x] `servicetalk-opentracing-log4j2` #1605
- [x] `servicetalk-opentracing-zipkin-publisher` #1606
- [x] `servicetalk-serialization-api` #1664
- [x] `servicetalk-tcp-netty-internal` #1664
- [x] `servicetalk-test-resources` #1664
- [x] `servicetalk-transport-api ` #1600
- [x] `servicetalk-transport-netty-internal` #1601 and #1780
- [x] `servicetalk-utils-internal` #1664
- [x] Remove jUnit4 dependency #1780

**Comment by amitvc** [comment]
@idelpivnitskiy Can I take up this task? I can start with servicetalk-client-api-internal, servicetalk-client-api and proceed down the list. Do you want a separate PR for each module? 
I am new to this project and willing to learn and understand the project. Just wanted to introduce myself. I have previous experience contributing to other open source projects as well.

**Comment by idelpivnitskiy** [comment]
Hi @amitvc,
Nice to e-meet you!

Sure, feel free to take some of the modules. Just post a comment here to let others know what modules you are working on. `servicetalk-client-api-internal` and `servicetalk-client-api` will be a good start. Then I will propose the following order: `logging`, `log4j2`, `oio`, `opentracing`, `encoding`.

Separate PRs will be preferable. Just use reasonable judgement to limit the scope and the size of the PR. It's ok to include more than one module in the PR if the modules are related.

**Comment by amitvc** [comment]
Hi @idelpivnitskiy nice to e-meet you as well 😄 
I am starting with servicetalk-client-api-internal first. I will have a PR for this module and then go onto the next.

**Comment by amitvc** [comment]
Hi @idelpivnitskiy I made changes for servicetalk-client-api-internal module. I am unable to build from command line. My gradle version is Gradle 5.0. I am getting following error -
`/Users/amit/Projects/servicetalk/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executors.java:224: error: unexpected heading used: <H2>, compared to implicit preceding heading: <H3>
     * <h2>Long running tasks</h2>
       ^
`

**Comment by idelpivnitskiy** [comment]
Regardless of what is the version of your local gradle, you can use gradlew script from the repository to make sure you use the same version as our CI:
```
./gradlew build
```

However, the error you see is generated by JDK, not gradle. It looks like you use some newer JDK version (JDK13+ with patch [JDK-8222528](https://bugs.openjdk.java.net/browse/JDK-8222528)). We did not try to build ST with newer versions, we check compatibility only with JDK8 and JDK11. Please, use one of these two.

**Comment by amitvc** [comment]
@idelpivnitskiy Thanks for getting back to me on this. I will switch to JDK8.

**Comment by amitvc** [comment]
@idelpivnitskiy when I am running Gradle build locally I am getting spotbug violation here [DefaultDnsClient](https://github.com/apple/servicetalk/blob/main/servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java#L628). It seems like resolutionObserver should not be nullable according to spotbug report. I am also getting similar error on H2ClientParentConnectionContext::childChannelActive where onCloseRunnable is Nullable

**Comment by amitvc** [comment]
My java version is - 
`Amits-MacBook-Pro:servicetalk amit$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)`

**Comment by idelpivnitskiy** [comment]
I believe this is a false positive report. I double checked both methods, those arguments have to be `@Nullable`. Spotbugs is known to produce false positive warnings. I'm not sure about difference between JDK 1.8.0_66 and the latest 8.0.292 (used by CI), but I saw difference in spotbugs results between JDK8 and JDK11. There are two workarounds I can propose:
1. Use the latest JDK8 version: 8.0.292.
2. Do not run `spotbugs` / `quality` / `build` tasks during local development. Use `test` and `checkstyle` instead. Spotbugs validation will be run on CI when you open a PR.

**Comment by kashike** [comment]
I have begun working on this as well, after being pointed to the servicetalk repository by @idelpivnitskiy while working on migrating tests over at netty.
- [x] `servicetalk-buffer-api` - #1592
- [x] `servicetalk-buffer-netty` - #1593

**Comment by idelpivnitskiy** [comment]
@kashike thank you for the contributions!

@amitvc do you need any help with initial set up?

**Comment by idelpivnitskiy** [comment]
I've created a list of all modules that contain `test` folder in the first message of this issue to track what is already converted and what is not.

**Comment by amitvc** [comment]
@idelpivnitskiy I have finished my code changes and pushed them to a branch. I went on vacation after that. I will pick up tonight and push a CR.

**Comment by kashike** [comment]
- [x] `servicetalk-transport-api` #1600

**Comment by kashike** [comment]
- [x] `servicetalk-transport-netty-internal` #1601

**Comment by idelpivnitskiy** [comment]
@amitvc np, just wanted to check if there is something that is blocking you. Enjoy vacation!

**Comment by kashike** [comment]
- [x] `servicetalk-opentracing-asynccontext` #1603
- [x] `servicetalk-opentracing-http` #1604
- [x] `servicetalk-opentracing-log4j2` #1605
- [x] `servicetalk-opentracing-zipkin-publisher` #1606

**Comment by kashike** [comment]
- [x] `servicetalk-dns-discovery-netty` #1607

**Comment by amitvc** [comment]
`servicetalk-client-api `https://github.com/apple/servicetalk/pull/1612

**Comment by danfaer** [comment]
in progress:

```
servicetalk-concurrent-jdkflow
servicetalk-concurrent-reactivestreams
servicetalk-data-jackson-jersey
servicetalk-http-router-jersey
```

**Comment by idelpivnitskiy** [comment]
@danfaer is working on migration of all other modules and will send PRs soon

**Comment by amitvc** [comment]
@idelpivnitskiy @danfaer are you working on these 
servicetalk-serialization-api
 servicetalk-tcp-netty-internal
 servicetalk-test-resources ? 
 If not I can pick them up.

**Comment by danfaer** [comment]
@amitvc Thanks for the offer! I already converted all modules. Will merge them in batches now.

**Comment by bondolo** [comment]
I checked following #1779 and only two modules still reference junit 4 as a dependency:

- servicetalk-transport-netty-internal
- servicetalk-concurrent-api

**Comment by bondolo** [comment]
Thanks to @danfaer, @amitvc and @kashike for your efforts in completing this valuable contribution!
